#ifndef __COUNT_DEFINITIONS_H__
#define __COUNT_DEFINITIONS_H__

#define STAGE_A_TOTAL_PASS			20
#define STAGE_B_TOTAL_PASS			25
#define STAGE_C_TOTAL_PASS			30
#define STAGE_D_TOTAL_PASS			30
#define STAGE_E_TOTAL_PASS			40

#define STAGE_A_TWOSTAR_NOMAL		10
#define STAGE_A_TWOSTAR_SPEED		1

#define STAGE_A_THREESTAR_NOMAL		12
#define STAGE_A_THREESTAR_SPEED		2
#define STAGE_A_THREESTAR_FAT		1

#define STAGE_B_TWOSTAR_NOMAL		15
#define STAGE_B_TWOSTAR_SPEED		3

#define STAGE_B_THREESTAR_NOMAL		18
#define STAGE_B_THREESTAR_SPEED		3
#define STAGE_B_THREESTAR_FAT		2

#define STAGE_C_TWOSTAR_NOMAL		20
#define STAGE_C_TWOSTAR_SPEED		3
#define STAGE_C_TWOSTAR_FAT			2

#define STAGE_C_THREESTAR_NOMAL		22
#define STAGE_C_THREESTAR_SPEED		4
#define STAGE_C_THREESTAR_FAT		2
#define STAGE_C_THREESTAR_PANDA		1

#define STAGE_D_TWOSTAR_NOMAL		25
#define STAGE_D_TWOSTAR_SPEED		5
#define STAGE_D_TWOSTAR_FAT			2

#define STAGE_D_THREESTAR_NOMAL		27
#define STAGE_D_THREESTAR_SPEED		6
#define STAGE_D_THREESTAR_FAT		2
#define STAGE_D_THREESTAR_SAEBI		1

#define STAGE_E_TWOSTAR_NOMAL		30
#define STAGE_E_TWOSTAR_SPEED		6
#define STAGE_E_TWOSTAR_FAT			2

#define STAGE_E_THREESTAR_NOMAL		33
#define STAGE_E_THREESTAR_SPEED		6
#define STAGE_E_THREESTAR_FAT		3
#define STAGE_E_THREESTAR_PANDA		1
#define STAGE_E_THREESTAR_SAEBI		1


#define TAG_LABEL_TWO_NOMAL			3333
#define TAG_LABEL_TWO_SPEED			3334
#define TAG_LABEL_TWO_FAT			3335

#define TAG_LABEL_THREE_NOMAL		3340
#define TAG_LABEL_THREE_SPEED		3341
#define TAG_LABEL_THREE_FAT			3342
#define TAG_LABEL_THREE_SAEBI		3343
#define TAG_LABEL_THREE_PANDA		3355

#endif